spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rest-project
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddlAuto: create
    openInView: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  data:
    web:
      pageable:
        max-page-size: 10

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
